apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aviary-environment.fullname" . }}-workspace
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aviary-environment.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
