apiVersion: v1
kind: Service
metadata:
  name: {{ include "aviary-environment.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aviary-environment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "aviary-environment.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.runtime.port }}
      targetPort: {{ .Values.runtime.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
